name: Create Release with Dependencies

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create ZIP file
        run: |
          mkdir dist
          zip -r dist/gravity-forms-eu-vat.zip . \
            -x "*.git*" \
            -x "*.github*" \
            -x ".gitignore" \
            -x "composer.json" \
            -x "composer.lock"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/woo-cps.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}